// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: src/booking/api/service.proto

package api

import (
	context "context"
	models "github.com/cobbinma/booking-platform/lib/protobuf/autogen/lang/go/booking/models"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetSlotResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Match               *models.Slot   `protobuf:"bytes,1,opt,name=match,proto3" json:"match,omitempty"`
	OtherAvailableSlots []*models.Slot `protobuf:"bytes,2,rep,name=otherAvailableSlots,proto3" json:"otherAvailableSlots,omitempty"`
}

func (x *GetSlotResponse) Reset() {
	*x = GetSlotResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_booking_api_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSlotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSlotResponse) ProtoMessage() {}

func (x *GetSlotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_booking_api_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSlotResponse.ProtoReflect.Descriptor instead.
func (*GetSlotResponse) Descriptor() ([]byte, []int) {
	return file_src_booking_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSlotResponse) GetMatch() *models.Slot {
	if x != nil {
		return x.Match
	}
	return nil
}

func (x *GetSlotResponse) GetOtherAvailableSlots() []*models.Slot {
	if x != nil {
		return x.OtherAvailableSlots
	}
	return nil
}

var File_src_booking_api_service_proto protoreflect.FileDescriptor

var file_src_booking_api_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1f, 0x73, 0x72,
	0x63, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x2a, 0x0a, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x52, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x46, 0x0a,
	0x13, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x53,
	0x6c, 0x6f, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x13, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x53, 0x6c, 0x6f, 0x74, 0x73, 0x32, 0x95, 0x01, 0x0a, 0x0a, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e,
	0x67, 0x41, 0x50, 0x49, 0x12, 0x42, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x74, 0x12,
	0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x1c, 0x2e, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x6f, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x12, 0x19, 0x2e, 0x62, 0x6f, 0x6f, 0x6b,
	0x69, 0x6e, 0x67, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x53, 0x6c, 0x6f, 0x74, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x17, 0x2e, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2e, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x42, 0x4f, 0x5a,
	0x4d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x62, 0x62,
	0x69, 0x6e, 0x6d, 0x61, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x70, 0x6c, 0x61,
	0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x2f,
	0x67, 0x6f, 0x2f, 0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_booking_api_service_proto_rawDescOnce sync.Once
	file_src_booking_api_service_proto_rawDescData = file_src_booking_api_service_proto_rawDesc
)

func file_src_booking_api_service_proto_rawDescGZIP() []byte {
	file_src_booking_api_service_proto_rawDescOnce.Do(func() {
		file_src_booking_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_booking_api_service_proto_rawDescData)
	})
	return file_src_booking_api_service_proto_rawDescData
}

var file_src_booking_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_booking_api_service_proto_goTypes = []interface{}{
	(*GetSlotResponse)(nil),  // 0: booking.api.GetSlotResponse
	(*models.Slot)(nil),      // 1: booking.models.Slot
	(*models.SlotInput)(nil), // 2: booking.models.SlotInput
	(*models.Booking)(nil),   // 3: booking.models.Booking
}
var file_src_booking_api_service_proto_depIdxs = []int32{
	1, // 0: booking.api.GetSlotResponse.match:type_name -> booking.models.Slot
	1, // 1: booking.api.GetSlotResponse.otherAvailableSlots:type_name -> booking.models.Slot
	2, // 2: booking.api.BookingAPI.GetSlot:input_type -> booking.models.SlotInput
	2, // 3: booking.api.BookingAPI.CreateBooking:input_type -> booking.models.SlotInput
	0, // 4: booking.api.BookingAPI.GetSlot:output_type -> booking.api.GetSlotResponse
	3, // 5: booking.api.BookingAPI.CreateBooking:output_type -> booking.models.Booking
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_booking_api_service_proto_init() }
func file_src_booking_api_service_proto_init() {
	if File_src_booking_api_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_booking_api_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSlotResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_booking_api_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_booking_api_service_proto_goTypes,
		DependencyIndexes: file_src_booking_api_service_proto_depIdxs,
		MessageInfos:      file_src_booking_api_service_proto_msgTypes,
	}.Build()
	File_src_booking_api_service_proto = out.File
	file_src_booking_api_service_proto_rawDesc = nil
	file_src_booking_api_service_proto_goTypes = nil
	file_src_booking_api_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BookingAPIClient is the client API for BookingAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingAPIClient interface {
	GetSlot(ctx context.Context, in *models.SlotInput, opts ...grpc.CallOption) (*GetSlotResponse, error)
	CreateBooking(ctx context.Context, in *models.SlotInput, opts ...grpc.CallOption) (*models.Booking, error)
}

type bookingAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingAPIClient(cc grpc.ClientConnInterface) BookingAPIClient {
	return &bookingAPIClient{cc}
}

func (c *bookingAPIClient) GetSlot(ctx context.Context, in *models.SlotInput, opts ...grpc.CallOption) (*GetSlotResponse, error) {
	out := new(GetSlotResponse)
	err := c.cc.Invoke(ctx, "/booking.api.BookingAPI/GetSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingAPIClient) CreateBooking(ctx context.Context, in *models.SlotInput, opts ...grpc.CallOption) (*models.Booking, error) {
	out := new(models.Booking)
	err := c.cc.Invoke(ctx, "/booking.api.BookingAPI/CreateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingAPIServer is the server API for BookingAPI service.
type BookingAPIServer interface {
	GetSlot(context.Context, *models.SlotInput) (*GetSlotResponse, error)
	CreateBooking(context.Context, *models.SlotInput) (*models.Booking, error)
}

// UnimplementedBookingAPIServer can be embedded to have forward compatible implementations.
type UnimplementedBookingAPIServer struct {
}

func (*UnimplementedBookingAPIServer) GetSlot(context.Context, *models.SlotInput) (*GetSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlot not implemented")
}
func (*UnimplementedBookingAPIServer) CreateBooking(context.Context, *models.SlotInput) (*models.Booking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}

func RegisterBookingAPIServer(s *grpc.Server, srv BookingAPIServer) {
	s.RegisterService(&_BookingAPI_serviceDesc, srv)
}

func _BookingAPI_GetSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.SlotInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingAPIServer).GetSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.api.BookingAPI/GetSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingAPIServer).GetSlot(ctx, req.(*models.SlotInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingAPI_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.SlotInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingAPIServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/booking.api.BookingAPI/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingAPIServer).CreateBooking(ctx, req.(*models.SlotInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookingAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "booking.api.BookingAPI",
	HandlerType: (*BookingAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSlot",
			Handler:    _BookingAPI_GetSlot_Handler,
		},
		{
			MethodName: "CreateBooking",
			Handler:    _BookingAPI_CreateBooking_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/booking/api/service.proto",
}
