// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Booking struct {
	ID         string    `json:"id"`
	VenueID    string    `json:"venueId"`
	CustomerID string    `json:"customerId"`
	People     int       `json:"people"`
	Date       string    `json:"date"`
	StartsAt   TimeOfDay `json:"startsAt"`
	EndsAt     TimeOfDay `json:"endsAt"`
	Duration   int       `json:"duration"`
	TableID    string    `json:"tableId"`
}

type BookingInput struct {
	ID         string    `json:"id"`
	VenueID    string    `json:"venueId"`
	CustomerID string    `json:"customerId"`
	People     int       `json:"people"`
	Date       string    `json:"date"`
	StartsAt   TimeOfDay `json:"startsAt"`
	Duration   int       `json:"duration"`
}

type OpeningHoursSpecification struct {
	DayOfWeek    int       `json:"dayOfWeek"`
	Opens        TimeOfDay `json:"opens"`
	Closes       TimeOfDay `json:"closes"`
	ValidFrom    *string   `json:"validFrom"`
	ValidThrough *string   `json:"validThrough"`
}

type Slot struct {
	ID         string    `json:"id"`
	VenueID    string    `json:"venueId"`
	CustomerID string    `json:"customerId"`
	People     int       `json:"people"`
	Date       string    `json:"date"`
	StartsAt   TimeOfDay `json:"startsAt"`
	EndsAt     TimeOfDay `json:"endsAt"`
	Duration   int       `json:"duration"`
}

type SlotInput struct {
	VenueID    string    `json:"venueId"`
	CustomerID string    `json:"customerId"`
	People     int       `json:"people"`
	Date       string    `json:"date"`
	StartsAt   TimeOfDay `json:"startsAt"`
	Duration   int       `json:"duration"`
}

type Venue struct {
	ID                  string                       `json:"id"`
	Name                string                       `json:"name"`
	OpeningHours        []*OpeningHoursSpecification `json:"openingHours"`
	SpecialOpeningHours []*OpeningHoursSpecification `json:"specialOpeningHours"`
}
