// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Booking struct {
	ID         string `json:"id"`
	VenueID    string `json:"venueId"`
	CustomerID string `json:"customerId"`
	People     int    `json:"people"`
	Date       string `json:"date"`
	StartsAt   string `json:"startsAt"`
	EndsAt     string `json:"endsAt"`
	Duration   int    `json:"duration"`
}

type BookingInput struct {
	ID         string `json:"id"`
	VenueID    string `json:"venueId"`
	CustomerID string `json:"customerId"`
	People     int    `json:"people"`
	Date       string `json:"date"`
	StartsAt   string `json:"startsAt"`
	Duration   int    `json:"duration"`
}

type OpeningHoursSpecification struct {
	DayOfWeek int    `json:"dayOfWeek"`
	Opens     string `json:"opens"`
	Closes    string `json:"closes"`
}

type Slot struct {
	ID         string `json:"id"`
	VenueID    string `json:"venueId"`
	CustomerID string `json:"customerId"`
	People     int    `json:"people"`
	Date       string `json:"date"`
	StartsAt   string `json:"startsAt"`
	EndsAt     string `json:"endsAt"`
	Duration   int    `json:"duration"`
}

type SlotInput struct {
	VenueID    string `json:"venueId"`
	CustomerID string `json:"customerId"`
	People     int    `json:"people"`
	Date       string `json:"date"`
	StartsAt   string `json:"startsAt"`
	Duration   int    `json:"duration"`
}

type Venue struct {
	ID           string                       `json:"id"`
	Name         string                       `json:"name"`
	OpeningHours []*OpeningHoursSpecification `json:"openingHours"`
}
