// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: src/venue/api/service.proto

package api

import (
	context "context"
	models "github.com/cobbinma/booking-platform/lib/protobuf/autogen/lang/go/venue/models"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetVenueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug string `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *GetVenueRequest) Reset() {
	*x = GetVenueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVenueRequest) ProtoMessage() {}

func (x *GetVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVenueRequest.ProtoReflect.Descriptor instead.
func (*GetVenueRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetVenueRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetVenueRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CreateVenueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string                              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	OpeningHours []*models.OpeningHoursSpecification `protobuf:"bytes,2,rep,name=openingHours,proto3" json:"openingHours,omitempty"`
	Slug         string                              `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *CreateVenueRequest) Reset() {
	*x = CreateVenueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateVenueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVenueRequest) ProtoMessage() {}

func (x *CreateVenueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVenueRequest.ProtoReflect.Descriptor instead.
func (*CreateVenueRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVenueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVenueRequest) GetOpeningHours() []*models.OpeningHoursSpecification {
	if x != nil {
		return x.OpeningHours
	}
	return nil
}

func (x *CreateVenueRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type GetTablesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
}

func (x *GetTablesRequest) Reset() {
	*x = GetTablesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTablesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesRequest) ProtoMessage() {}

func (x *GetTablesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesRequest.ProtoReflect.Descriptor instead.
func (*GetTablesRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTablesRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

type GetTablesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tables []*models.Table `protobuf:"bytes,1,rep,name=tables,proto3" json:"tables,omitempty"`
}

func (x *GetTablesResponse) Reset() {
	*x = GetTablesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTablesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTablesResponse) ProtoMessage() {}

func (x *GetTablesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTablesResponse.ProtoReflect.Descriptor instead.
func (*GetTablesResponse) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTablesResponse) GetTables() []*models.Table {
	if x != nil {
		return x.Tables
	}
	return nil
}

type GetOpeningHoursSpecificationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	Date    string `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *GetOpeningHoursSpecificationRequest) Reset() {
	*x = GetOpeningHoursSpecificationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpeningHoursSpecificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpeningHoursSpecificationRequest) ProtoMessage() {}

func (x *GetOpeningHoursSpecificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpeningHoursSpecificationRequest.ProtoReflect.Descriptor instead.
func (*GetOpeningHoursSpecificationRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetOpeningHoursSpecificationRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *GetOpeningHoursSpecificationRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type GetOpeningHoursSpecificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Specification *models.OpeningHoursSpecification `protobuf:"bytes,1,opt,name=specification,proto3" json:"specification,omitempty"`
}

func (x *GetOpeningHoursSpecificationResponse) Reset() {
	*x = GetOpeningHoursSpecificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOpeningHoursSpecificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpeningHoursSpecificationResponse) ProtoMessage() {}

func (x *GetOpeningHoursSpecificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpeningHoursSpecificationResponse.ProtoReflect.Descriptor instead.
func (*GetOpeningHoursSpecificationResponse) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetOpeningHoursSpecificationResponse) GetSpecification() *models.OpeningHoursSpecification {
	if x != nil {
		return x.Specification
	}
	return nil
}

type AddTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId  string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity uint32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
}

func (x *AddTableRequest) Reset() {
	*x = AddTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTableRequest) ProtoMessage() {}

func (x *AddTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTableRequest.ProtoReflect.Descriptor instead.
func (*AddTableRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{6}
}

func (x *AddTableRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *AddTableRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddTableRequest) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type RemoveTableRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	TableId string `protobuf:"bytes,2,opt,name=tableId,proto3" json:"tableId,omitempty"`
}

func (x *RemoveTableRequest) Reset() {
	*x = RemoveTableRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTableRequest) ProtoMessage() {}

func (x *RemoveTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTableRequest.ProtoReflect.Descriptor instead.
func (*RemoveTableRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveTableRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *RemoveTableRequest) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type IsAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	Email   string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Slug    string `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
}

func (x *IsAdminRequest) Reset() {
	*x = IsAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminRequest) ProtoMessage() {}

func (x *IsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminRequest.ProtoReflect.Descriptor instead.
func (*IsAdminRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{8}
}

func (x *IsAdminRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *IsAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *IsAdminRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type IsAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsAdmin bool `protobuf:"varint,1,opt,name=isAdmin,proto3" json:"isAdmin,omitempty"`
}

func (x *IsAdminResponse) Reset() {
	*x = IsAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IsAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsAdminResponse) ProtoMessage() {}

func (x *IsAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsAdminResponse.ProtoReflect.Descriptor instead.
func (*IsAdminResponse) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{9}
}

func (x *IsAdminResponse) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type GetAdminsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
}

func (x *GetAdminsRequest) Reset() {
	*x = GetAdminsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdminsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminsRequest) ProtoMessage() {}

func (x *GetAdminsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminsRequest.ProtoReflect.Descriptor instead.
func (*GetAdminsRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetAdminsRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

type GetAdminsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Admins []string `protobuf:"bytes,1,rep,name=admins,proto3" json:"admins,omitempty"`
}

func (x *GetAdminsResponse) Reset() {
	*x = GetAdminsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdminsResponse) ProtoMessage() {}

func (x *GetAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdminsResponse.ProtoReflect.Descriptor instead.
func (*GetAdminsResponse) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAdminsResponse) GetAdmins() []string {
	if x != nil {
		return x.Admins
	}
	return nil
}

type AddAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	Email   string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *AddAdminRequest) Reset() {
	*x = AddAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminRequest) ProtoMessage() {}

func (x *AddAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminRequest.ProtoReflect.Descriptor instead.
func (*AddAdminRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{12}
}

func (x *AddAdminRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *AddAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AddAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	Email   string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *AddAdminResponse) Reset() {
	*x = AddAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminResponse) ProtoMessage() {}

func (x *AddAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminResponse.ProtoReflect.Descriptor instead.
func (*AddAdminResponse) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{13}
}

func (x *AddAdminResponse) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *AddAdminResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemoveAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId string `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	Email   string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RemoveAdminRequest) Reset() {
	*x = RemoveAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminRequest) ProtoMessage() {}

func (x *RemoveAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminRequest.ProtoReflect.Descriptor instead.
func (*RemoveAdminRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveAdminRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *RemoveAdminRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type RemoveAdminResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *RemoveAdminResponse) Reset() {
	*x = RemoveAdminResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAdminResponse) ProtoMessage() {}

func (x *RemoveAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAdminResponse.ProtoReflect.Descriptor instead.
func (*RemoveAdminResponse) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveAdminResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UpdateOpeningHoursRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VenueId      string                              `protobuf:"bytes,1,opt,name=venueId,proto3" json:"venueId,omitempty"`
	OpeningHours []*models.OpeningHoursSpecification `protobuf:"bytes,2,rep,name=openingHours,proto3" json:"openingHours,omitempty"`
}

func (x *UpdateOpeningHoursRequest) Reset() {
	*x = UpdateOpeningHoursRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOpeningHoursRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOpeningHoursRequest) ProtoMessage() {}

func (x *UpdateOpeningHoursRequest) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOpeningHoursRequest.ProtoReflect.Descriptor instead.
func (*UpdateOpeningHoursRequest) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateOpeningHoursRequest) GetVenueId() string {
	if x != nil {
		return x.VenueId
	}
	return ""
}

func (x *UpdateOpeningHoursRequest) GetOpeningHours() []*models.OpeningHoursSpecification {
	if x != nil {
		return x.OpeningHours
	}
	return nil
}

type UpdateOpeningHoursResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OpeningHours []*models.OpeningHoursSpecification `protobuf:"bytes,1,rep,name=openingHours,proto3" json:"openingHours,omitempty"`
}

func (x *UpdateOpeningHoursResponse) Reset() {
	*x = UpdateOpeningHoursResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_api_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateOpeningHoursResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOpeningHoursResponse) ProtoMessage() {}

func (x *UpdateOpeningHoursResponse) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_api_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOpeningHoursResponse.ProtoReflect.Descriptor instead.
func (*UpdateOpeningHoursResponse) Descriptor() ([]byte, []int) {
	return file_src_venue_api_service_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateOpeningHoursResponse) GetOpeningHours() []*models.OpeningHoursSpecification {
	if x != nil {
		return x.OpeningHours
	}
	return nil
}

var File_src_venue_api_service_proto protoreflect.FileDescriptor

var file_src_venue_api_service_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x72, 0x63, 0x2f, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76,
	0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x1a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x76, 0x65,
	0x6e, 0x75, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c,
	0x75, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x89,
	0x01, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x6f, 0x70, 0x65,
	0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f,
	0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e,
	0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x22, 0x2c, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a,
	0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x06, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x22, 0x53, 0x0a, 0x23, 0x47, 0x65,
	0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x22,
	0x75, 0x0a, 0x24, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x70,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0d, 0x73, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e,
	0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75,
	0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63,
	0x69, 0x74, 0x79, 0x22, 0x48, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e,
	0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75,
	0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x54, 0x0a,
	0x0e, 0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x73, 0x6c, 0x75, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73,
	0x6c, 0x75, 0x67, 0x22, 0x2b, 0x0a, 0x0f, 0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x22, 0x2c, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x22, 0x2b,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x22, 0x41, 0x0a, 0x0f, 0x41,
	0x64, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x42,
	0x0a, 0x10, 0x41, 0x64, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x22, 0x44, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75,
	0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x2b, 0x0a, 0x13, 0x52, 0x65, 0x6d, 0x6f,
	0x76, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x82, 0x01, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x49, 0x64, 0x12, 0x4b, 0x0a,
	0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6f, 0x70,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x22, 0x69, 0x0a, 0x1a, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x70,
	0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67,
	0x48, 0x6f, 0x75, 0x72, 0x73, 0x32, 0xbd, 0x07, 0x0a, 0x08, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x41,
	0x50, 0x49, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x1a,
	0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x76, 0x65, 0x6e,
	0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x12,
	0x41, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x1d,
	0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x56, 0x65, 0x6e,
	0x75, 0x65, 0x12, 0x61, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x24, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x69,
	0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x68, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x12, 0x24, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4f, 0x70, 0x65, 0x6e, 0x69,
	0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x7f, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75,
	0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2e, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4f,
	0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2f, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x4f,
	0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x46, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x2e,
	0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x65, 0x6e,
	0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x64, 0x64, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x41, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x40, 0x0a, 0x07, 0x49, 0x73, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x12, 0x19, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x73, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x08, 0x41, 0x64,
	0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1a, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41,
	0x64, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x46, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x76,
	0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x76, 0x65, 0x6e, 0x75,
	0x65, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1d, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x62, 0x62, 0x69, 0x6e, 0x6d, 0x61, 0x2f, 0x62, 0x6f, 0x6f,
	0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x6c, 0x69,
	0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x75, 0x74, 0x6f, 0x67,
	0x65, 0x6e, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x65, 0x6e, 0x75, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_venue_api_service_proto_rawDescOnce sync.Once
	file_src_venue_api_service_proto_rawDescData = file_src_venue_api_service_proto_rawDesc
)

func file_src_venue_api_service_proto_rawDescGZIP() []byte {
	file_src_venue_api_service_proto_rawDescOnce.Do(func() {
		file_src_venue_api_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_venue_api_service_proto_rawDescData)
	})
	return file_src_venue_api_service_proto_rawDescData
}

var file_src_venue_api_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_src_venue_api_service_proto_goTypes = []interface{}{
	(*GetVenueRequest)(nil),                      // 0: venue.api.GetVenueRequest
	(*CreateVenueRequest)(nil),                   // 1: venue.api.CreateVenueRequest
	(*GetTablesRequest)(nil),                     // 2: venue.api.GetTablesRequest
	(*GetTablesResponse)(nil),                    // 3: venue.api.GetTablesResponse
	(*GetOpeningHoursSpecificationRequest)(nil),  // 4: venue.api.GetOpeningHoursSpecificationRequest
	(*GetOpeningHoursSpecificationResponse)(nil), // 5: venue.api.GetOpeningHoursSpecificationResponse
	(*AddTableRequest)(nil),                      // 6: venue.api.AddTableRequest
	(*RemoveTableRequest)(nil),                   // 7: venue.api.RemoveTableRequest
	(*IsAdminRequest)(nil),                       // 8: venue.api.IsAdminRequest
	(*IsAdminResponse)(nil),                      // 9: venue.api.IsAdminResponse
	(*GetAdminsRequest)(nil),                     // 10: venue.api.GetAdminsRequest
	(*GetAdminsResponse)(nil),                    // 11: venue.api.GetAdminsResponse
	(*AddAdminRequest)(nil),                      // 12: venue.api.AddAdminRequest
	(*AddAdminResponse)(nil),                     // 13: venue.api.AddAdminResponse
	(*RemoveAdminRequest)(nil),                   // 14: venue.api.RemoveAdminRequest
	(*RemoveAdminResponse)(nil),                  // 15: venue.api.RemoveAdminResponse
	(*UpdateOpeningHoursRequest)(nil),            // 16: venue.api.UpdateOpeningHoursRequest
	(*UpdateOpeningHoursResponse)(nil),           // 17: venue.api.UpdateOpeningHoursResponse
	(*models.OpeningHoursSpecification)(nil),     // 18: venue.models.OpeningHoursSpecification
	(*models.Table)(nil),                         // 19: venue.models.Table
	(*models.Venue)(nil),                         // 20: venue.models.Venue
}
var file_src_venue_api_service_proto_depIdxs = []int32{
	18, // 0: venue.api.CreateVenueRequest.openingHours:type_name -> venue.models.OpeningHoursSpecification
	19, // 1: venue.api.GetTablesResponse.tables:type_name -> venue.models.Table
	18, // 2: venue.api.GetOpeningHoursSpecificationResponse.specification:type_name -> venue.models.OpeningHoursSpecification
	18, // 3: venue.api.UpdateOpeningHoursRequest.openingHours:type_name -> venue.models.OpeningHoursSpecification
	18, // 4: venue.api.UpdateOpeningHoursResponse.openingHours:type_name -> venue.models.OpeningHoursSpecification
	0,  // 5: venue.api.VenueAPI.GetVenue:input_type -> venue.api.GetVenueRequest
	1,  // 6: venue.api.VenueAPI.CreateVenue:input_type -> venue.api.CreateVenueRequest
	16, // 7: venue.api.VenueAPI.UpdateOpeningHours:input_type -> venue.api.UpdateOpeningHoursRequest
	16, // 8: venue.api.VenueAPI.UpdateSpecialOpeningHours:input_type -> venue.api.UpdateOpeningHoursRequest
	4,  // 9: venue.api.VenueAPI.GetOpeningHoursSpecification:input_type -> venue.api.GetOpeningHoursSpecificationRequest
	2,  // 10: venue.api.VenueAPI.GetTables:input_type -> venue.api.GetTablesRequest
	6,  // 11: venue.api.VenueAPI.AddTable:input_type -> venue.api.AddTableRequest
	7,  // 12: venue.api.VenueAPI.RemoveTable:input_type -> venue.api.RemoveTableRequest
	8,  // 13: venue.api.VenueAPI.IsAdmin:input_type -> venue.api.IsAdminRequest
	12, // 14: venue.api.VenueAPI.AddAdmin:input_type -> venue.api.AddAdminRequest
	10, // 15: venue.api.VenueAPI.GetAdmins:input_type -> venue.api.GetAdminsRequest
	14, // 16: venue.api.VenueAPI.RemoveAdmin:input_type -> venue.api.RemoveAdminRequest
	20, // 17: venue.api.VenueAPI.GetVenue:output_type -> venue.models.Venue
	20, // 18: venue.api.VenueAPI.CreateVenue:output_type -> venue.models.Venue
	17, // 19: venue.api.VenueAPI.UpdateOpeningHours:output_type -> venue.api.UpdateOpeningHoursResponse
	17, // 20: venue.api.VenueAPI.UpdateSpecialOpeningHours:output_type -> venue.api.UpdateOpeningHoursResponse
	5,  // 21: venue.api.VenueAPI.GetOpeningHoursSpecification:output_type -> venue.api.GetOpeningHoursSpecificationResponse
	3,  // 22: venue.api.VenueAPI.GetTables:output_type -> venue.api.GetTablesResponse
	19, // 23: venue.api.VenueAPI.AddTable:output_type -> venue.models.Table
	19, // 24: venue.api.VenueAPI.RemoveTable:output_type -> venue.models.Table
	9,  // 25: venue.api.VenueAPI.IsAdmin:output_type -> venue.api.IsAdminResponse
	13, // 26: venue.api.VenueAPI.AddAdmin:output_type -> venue.api.AddAdminResponse
	11, // 27: venue.api.VenueAPI.GetAdmins:output_type -> venue.api.GetAdminsResponse
	15, // 28: venue.api.VenueAPI.RemoveAdmin:output_type -> venue.api.RemoveAdminResponse
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_src_venue_api_service_proto_init() }
func file_src_venue_api_service_proto_init() {
	if File_src_venue_api_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_venue_api_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVenueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateVenueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTablesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTablesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpeningHoursSpecificationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOpeningHoursSpecificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveTableRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IsAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdminsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAdminsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveAdminResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOpeningHoursRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_api_service_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateOpeningHoursResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_venue_api_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_src_venue_api_service_proto_goTypes,
		DependencyIndexes: file_src_venue_api_service_proto_depIdxs,
		MessageInfos:      file_src_venue_api_service_proto_msgTypes,
	}.Build()
	File_src_venue_api_service_proto = out.File
	file_src_venue_api_service_proto_rawDesc = nil
	file_src_venue_api_service_proto_goTypes = nil
	file_src_venue_api_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VenueAPIClient is the client API for VenueAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VenueAPIClient interface {
	GetVenue(ctx context.Context, in *GetVenueRequest, opts ...grpc.CallOption) (*models.Venue, error)
	CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*models.Venue, error)
	UpdateOpeningHours(ctx context.Context, in *UpdateOpeningHoursRequest, opts ...grpc.CallOption) (*UpdateOpeningHoursResponse, error)
	UpdateSpecialOpeningHours(ctx context.Context, in *UpdateOpeningHoursRequest, opts ...grpc.CallOption) (*UpdateOpeningHoursResponse, error)
	GetOpeningHoursSpecification(ctx context.Context, in *GetOpeningHoursSpecificationRequest, opts ...grpc.CallOption) (*GetOpeningHoursSpecificationResponse, error)
	GetTables(ctx context.Context, in *GetTablesRequest, opts ...grpc.CallOption) (*GetTablesResponse, error)
	AddTable(ctx context.Context, in *AddTableRequest, opts ...grpc.CallOption) (*models.Table, error)
	RemoveTable(ctx context.Context, in *RemoveTableRequest, opts ...grpc.CallOption) (*models.Table, error)
	IsAdmin(ctx context.Context, in *IsAdminRequest, opts ...grpc.CallOption) (*IsAdminResponse, error)
	AddAdmin(ctx context.Context, in *AddAdminRequest, opts ...grpc.CallOption) (*AddAdminResponse, error)
	GetAdmins(ctx context.Context, in *GetAdminsRequest, opts ...grpc.CallOption) (*GetAdminsResponse, error)
	RemoveAdmin(ctx context.Context, in *RemoveAdminRequest, opts ...grpc.CallOption) (*RemoveAdminResponse, error)
}

type venueAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewVenueAPIClient(cc grpc.ClientConnInterface) VenueAPIClient {
	return &venueAPIClient{cc}
}

func (c *venueAPIClient) GetVenue(ctx context.Context, in *GetVenueRequest, opts ...grpc.CallOption) (*models.Venue, error) {
	out := new(models.Venue)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/GetVenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) CreateVenue(ctx context.Context, in *CreateVenueRequest, opts ...grpc.CallOption) (*models.Venue, error) {
	out := new(models.Venue)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/CreateVenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) UpdateOpeningHours(ctx context.Context, in *UpdateOpeningHoursRequest, opts ...grpc.CallOption) (*UpdateOpeningHoursResponse, error) {
	out := new(UpdateOpeningHoursResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/UpdateOpeningHours", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) UpdateSpecialOpeningHours(ctx context.Context, in *UpdateOpeningHoursRequest, opts ...grpc.CallOption) (*UpdateOpeningHoursResponse, error) {
	out := new(UpdateOpeningHoursResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/UpdateSpecialOpeningHours", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) GetOpeningHoursSpecification(ctx context.Context, in *GetOpeningHoursSpecificationRequest, opts ...grpc.CallOption) (*GetOpeningHoursSpecificationResponse, error) {
	out := new(GetOpeningHoursSpecificationResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/GetOpeningHoursSpecification", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) GetTables(ctx context.Context, in *GetTablesRequest, opts ...grpc.CallOption) (*GetTablesResponse, error) {
	out := new(GetTablesResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/GetTables", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) AddTable(ctx context.Context, in *AddTableRequest, opts ...grpc.CallOption) (*models.Table, error) {
	out := new(models.Table)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/AddTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) RemoveTable(ctx context.Context, in *RemoveTableRequest, opts ...grpc.CallOption) (*models.Table, error) {
	out := new(models.Table)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/RemoveTable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) IsAdmin(ctx context.Context, in *IsAdminRequest, opts ...grpc.CallOption) (*IsAdminResponse, error) {
	out := new(IsAdminResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/IsAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) AddAdmin(ctx context.Context, in *AddAdminRequest, opts ...grpc.CallOption) (*AddAdminResponse, error) {
	out := new(AddAdminResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/AddAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) GetAdmins(ctx context.Context, in *GetAdminsRequest, opts ...grpc.CallOption) (*GetAdminsResponse, error) {
	out := new(GetAdminsResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/GetAdmins", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *venueAPIClient) RemoveAdmin(ctx context.Context, in *RemoveAdminRequest, opts ...grpc.CallOption) (*RemoveAdminResponse, error) {
	out := new(RemoveAdminResponse)
	err := c.cc.Invoke(ctx, "/venue.api.VenueAPI/RemoveAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VenueAPIServer is the server API for VenueAPI service.
type VenueAPIServer interface {
	GetVenue(context.Context, *GetVenueRequest) (*models.Venue, error)
	CreateVenue(context.Context, *CreateVenueRequest) (*models.Venue, error)
	UpdateOpeningHours(context.Context, *UpdateOpeningHoursRequest) (*UpdateOpeningHoursResponse, error)
	UpdateSpecialOpeningHours(context.Context, *UpdateOpeningHoursRequest) (*UpdateOpeningHoursResponse, error)
	GetOpeningHoursSpecification(context.Context, *GetOpeningHoursSpecificationRequest) (*GetOpeningHoursSpecificationResponse, error)
	GetTables(context.Context, *GetTablesRequest) (*GetTablesResponse, error)
	AddTable(context.Context, *AddTableRequest) (*models.Table, error)
	RemoveTable(context.Context, *RemoveTableRequest) (*models.Table, error)
	IsAdmin(context.Context, *IsAdminRequest) (*IsAdminResponse, error)
	AddAdmin(context.Context, *AddAdminRequest) (*AddAdminResponse, error)
	GetAdmins(context.Context, *GetAdminsRequest) (*GetAdminsResponse, error)
	RemoveAdmin(context.Context, *RemoveAdminRequest) (*RemoveAdminResponse, error)
}

// UnimplementedVenueAPIServer can be embedded to have forward compatible implementations.
type UnimplementedVenueAPIServer struct {
}

func (*UnimplementedVenueAPIServer) GetVenue(context.Context, *GetVenueRequest) (*models.Venue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVenue not implemented")
}
func (*UnimplementedVenueAPIServer) CreateVenue(context.Context, *CreateVenueRequest) (*models.Venue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVenue not implemented")
}
func (*UnimplementedVenueAPIServer) UpdateOpeningHours(context.Context, *UpdateOpeningHoursRequest) (*UpdateOpeningHoursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOpeningHours not implemented")
}
func (*UnimplementedVenueAPIServer) UpdateSpecialOpeningHours(context.Context, *UpdateOpeningHoursRequest) (*UpdateOpeningHoursResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpecialOpeningHours not implemented")
}
func (*UnimplementedVenueAPIServer) GetOpeningHoursSpecification(context.Context, *GetOpeningHoursSpecificationRequest) (*GetOpeningHoursSpecificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOpeningHoursSpecification not implemented")
}
func (*UnimplementedVenueAPIServer) GetTables(context.Context, *GetTablesRequest) (*GetTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTables not implemented")
}
func (*UnimplementedVenueAPIServer) AddTable(context.Context, *AddTableRequest) (*models.Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTable not implemented")
}
func (*UnimplementedVenueAPIServer) RemoveTable(context.Context, *RemoveTableRequest) (*models.Table, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTable not implemented")
}
func (*UnimplementedVenueAPIServer) IsAdmin(context.Context, *IsAdminRequest) (*IsAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAdmin not implemented")
}
func (*UnimplementedVenueAPIServer) AddAdmin(context.Context, *AddAdminRequest) (*AddAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAdmin not implemented")
}
func (*UnimplementedVenueAPIServer) GetAdmins(context.Context, *GetAdminsRequest) (*GetAdminsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAdmins not implemented")
}
func (*UnimplementedVenueAPIServer) RemoveAdmin(context.Context, *RemoveAdminRequest) (*RemoveAdminResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveAdmin not implemented")
}

func RegisterVenueAPIServer(s *grpc.Server, srv VenueAPIServer) {
	s.RegisterService(&_VenueAPI_serviceDesc, srv)
}

func _VenueAPI_GetVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).GetVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/GetVenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).GetVenue(ctx, req.(*GetVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_CreateVenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).CreateVenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/CreateVenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).CreateVenue(ctx, req.(*CreateVenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_UpdateOpeningHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOpeningHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).UpdateOpeningHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/UpdateOpeningHours",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).UpdateOpeningHours(ctx, req.(*UpdateOpeningHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_UpdateSpecialOpeningHours_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOpeningHoursRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).UpdateSpecialOpeningHours(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/UpdateSpecialOpeningHours",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).UpdateSpecialOpeningHours(ctx, req.(*UpdateOpeningHoursRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_GetOpeningHoursSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpeningHoursSpecificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).GetOpeningHoursSpecification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/GetOpeningHoursSpecification",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).GetOpeningHoursSpecification(ctx, req.(*GetOpeningHoursSpecificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_GetTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).GetTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/GetTables",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).GetTables(ctx, req.(*GetTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_AddTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).AddTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/AddTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).AddTable(ctx, req.(*AddTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_RemoveTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).RemoveTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/RemoveTable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).RemoveTable(ctx, req.(*RemoveTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_IsAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).IsAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/IsAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).IsAdmin(ctx, req.(*IsAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_AddAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).AddAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/AddAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).AddAdmin(ctx, req.(*AddAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_GetAdmins_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdminsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).GetAdmins(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/GetAdmins",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).GetAdmins(ctx, req.(*GetAdminsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VenueAPI_RemoveAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VenueAPIServer).RemoveAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/venue.api.VenueAPI/RemoveAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VenueAPIServer).RemoveAdmin(ctx, req.(*RemoveAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VenueAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "venue.api.VenueAPI",
	HandlerType: (*VenueAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVenue",
			Handler:    _VenueAPI_GetVenue_Handler,
		},
		{
			MethodName: "CreateVenue",
			Handler:    _VenueAPI_CreateVenue_Handler,
		},
		{
			MethodName: "UpdateOpeningHours",
			Handler:    _VenueAPI_UpdateOpeningHours_Handler,
		},
		{
			MethodName: "UpdateSpecialOpeningHours",
			Handler:    _VenueAPI_UpdateSpecialOpeningHours_Handler,
		},
		{
			MethodName: "GetOpeningHoursSpecification",
			Handler:    _VenueAPI_GetOpeningHoursSpecification_Handler,
		},
		{
			MethodName: "GetTables",
			Handler:    _VenueAPI_GetTables_Handler,
		},
		{
			MethodName: "AddTable",
			Handler:    _VenueAPI_AddTable_Handler,
		},
		{
			MethodName: "RemoveTable",
			Handler:    _VenueAPI_RemoveTable_Handler,
		},
		{
			MethodName: "IsAdmin",
			Handler:    _VenueAPI_IsAdmin_Handler,
		},
		{
			MethodName: "AddAdmin",
			Handler:    _VenueAPI_AddAdmin_Handler,
		},
		{
			MethodName: "GetAdmins",
			Handler:    _VenueAPI_GetAdmins_Handler,
		},
		{
			MethodName: "RemoveAdmin",
			Handler:    _VenueAPI_RemoveAdmin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/venue/api/service.proto",
}
