// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: src/venue/models/models.proto

package models

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Venue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OpeningHours        []*OpeningHoursSpecification `protobuf:"bytes,3,rep,name=openingHours,proto3" json:"openingHours,omitempty"`
	SpecialOpeningHours []*OpeningHoursSpecification `protobuf:"bytes,4,rep,name=specialOpeningHours,proto3" json:"specialOpeningHours,omitempty"`
}

func (x *Venue) Reset() {
	*x = Venue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_models_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Venue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Venue) ProtoMessage() {}

func (x *Venue) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_models_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Venue.ProtoReflect.Descriptor instead.
func (*Venue) Descriptor() ([]byte, []int) {
	return file_src_venue_models_models_proto_rawDescGZIP(), []int{0}
}

func (x *Venue) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Venue) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Venue) GetOpeningHours() []*OpeningHoursSpecification {
	if x != nil {
		return x.OpeningHours
	}
	return nil
}

func (x *Venue) GetSpecialOpeningHours() []*OpeningHoursSpecification {
	if x != nil {
		return x.SpecialOpeningHours
	}
	return nil
}

type OpeningHoursSpecification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DayOfWeek    uint32 `protobuf:"varint,1,opt,name=dayOfWeek,proto3" json:"dayOfWeek,omitempty"`
	Opens        string `protobuf:"bytes,2,opt,name=opens,proto3" json:"opens,omitempty"`
	Closes       string `protobuf:"bytes,3,opt,name=closes,proto3" json:"closes,omitempty"`
	ValidFrom    string `protobuf:"bytes,4,opt,name=validFrom,proto3" json:"validFrom,omitempty"`
	ValidThrough string `protobuf:"bytes,5,opt,name=validThrough,proto3" json:"validThrough,omitempty"`
}

func (x *OpeningHoursSpecification) Reset() {
	*x = OpeningHoursSpecification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_models_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpeningHoursSpecification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpeningHoursSpecification) ProtoMessage() {}

func (x *OpeningHoursSpecification) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_models_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpeningHoursSpecification.ProtoReflect.Descriptor instead.
func (*OpeningHoursSpecification) Descriptor() ([]byte, []int) {
	return file_src_venue_models_models_proto_rawDescGZIP(), []int{1}
}

func (x *OpeningHoursSpecification) GetDayOfWeek() uint32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *OpeningHoursSpecification) GetOpens() string {
	if x != nil {
		return x.Opens
	}
	return ""
}

func (x *OpeningHoursSpecification) GetCloses() string {
	if x != nil {
		return x.Closes
	}
	return ""
}

func (x *OpeningHoursSpecification) GetValidFrom() string {
	if x != nil {
		return x.ValidFrom
	}
	return ""
}

func (x *OpeningHoursSpecification) GetValidThrough() string {
	if x != nil {
		return x.ValidThrough
	}
	return ""
}

type Table struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Capacity uint32 `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
}

func (x *Table) Reset() {
	*x = Table{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_venue_models_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_src_venue_models_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_src_venue_models_models_proto_rawDescGZIP(), []int{2}
}

func (x *Table) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Table) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Table) GetCapacity() uint32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

var File_src_venue_models_models_proto protoreflect.FileDescriptor

var file_src_venue_models_models_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x22, 0xd3, 0x01,
	0x0a, 0x05, 0x56, 0x65, 0x6e, 0x75, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x6f,
	0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x27, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65,
	0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x59, 0x0a, 0x13, 0x73, 0x70, 0x65, 0x63,
	0x69, 0x61, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x76, 0x65, 0x6e, 0x75, 0x65, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72,
	0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x13,
	0x73, 0x70, 0x65, 0x63, 0x69, 0x61, 0x6c, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48, 0x6f,
	0x75, 0x72, 0x73, 0x22, 0xa9, 0x01, 0x0a, 0x19, 0x4f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x48,
	0x6f, 0x75, 0x72, 0x73, 0x53, 0x70, 0x65, 0x63, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x79, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64, 0x61, 0x79, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x12,
	0x14, 0x0a, 0x05, 0x6f, 0x70, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6f, 0x70, 0x65, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x73, 0x12, 0x1c, 0x0a,
	0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x76,
	0x61, 0x6c, 0x69, 0x64, 0x54, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x54, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68, 0x22,
	0x47, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x42, 0x50, 0x5a, 0x4e, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x62, 0x62, 0x69, 0x6e, 0x6d, 0x61, 0x2f,
	0x62, 0x6f, 0x6f, 0x6b, 0x69, 0x6e, 0x67, 0x2d, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x2f, 0x6c, 0x69, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x75,
	0x74, 0x6f, 0x67, 0x65, 0x6e, 0x2f, 0x6c, 0x61, 0x6e, 0x67, 0x2f, 0x67, 0x6f, 0x2f, 0x76, 0x65,
	0x6e, 0x75, 0x65, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_src_venue_models_models_proto_rawDescOnce sync.Once
	file_src_venue_models_models_proto_rawDescData = file_src_venue_models_models_proto_rawDesc
)

func file_src_venue_models_models_proto_rawDescGZIP() []byte {
	file_src_venue_models_models_proto_rawDescOnce.Do(func() {
		file_src_venue_models_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_venue_models_models_proto_rawDescData)
	})
	return file_src_venue_models_models_proto_rawDescData
}

var file_src_venue_models_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_venue_models_models_proto_goTypes = []interface{}{
	(*Venue)(nil),                     // 0: venue.models.Venue
	(*OpeningHoursSpecification)(nil), // 1: venue.models.OpeningHoursSpecification
	(*Table)(nil),                     // 2: venue.models.Table
}
var file_src_venue_models_models_proto_depIdxs = []int32{
	1, // 0: venue.models.Venue.openingHours:type_name -> venue.models.OpeningHoursSpecification
	1, // 1: venue.models.Venue.specialOpeningHours:type_name -> venue.models.OpeningHoursSpecification
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_src_venue_models_models_proto_init() }
func file_src_venue_models_models_proto_init() {
	if File_src_venue_models_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_venue_models_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Venue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_models_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpeningHoursSpecification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_venue_models_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Table); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_venue_models_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_venue_models_models_proto_goTypes,
		DependencyIndexes: file_src_venue_models_models_proto_depIdxs,
		MessageInfos:      file_src_venue_models_models_proto_msgTypes,
	}.Build()
	File_src_venue_models_models_proto = out.File
	file_src_venue_models_models_proto_rawDesc = nil
	file_src_venue_models_models_proto_goTypes = nil
	file_src_venue_models_models_proto_depIdxs = nil
}
